apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base/model

commonLabels:
  env: prod

namespace: model-prod

patches:
  - path: patch-rollout-podlabels.yaml
  - path: patch-analysis-namespace.yaml
  - path: patch-analysistemplate-args.yaml
  - path: patch-servicemonitor-namespace.yaml
  - path: patch-service-active-env.yaml
  - path: patch-service-preview-env.yaml
