apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base/model
  - keda-rollouts-rbac.yaml

commonLabels:
  env: prod

namespace: model-prod

configMapGenerator:
  - name: env-vars
    behavior: replace
    literals:
      - NAMESPACE=model-prod

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: model
    path: patch-rollout-env-selector.yaml

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: model
    path: patch-rollout-analysis-namespace.yaml

  - path: patch-rollout-podlabels.yaml
  - path: patch-servicemonitor-namespace.yaml
  - path: patch-service-active-env.yaml
  - path: patch-service-preview-env.yaml

images:
  - name: docker.io/joevisco/house-pricemodel
    newTag: sha-ae04857
