apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base/model
commonLabels:
  env: staging
namespace: model-staging
configMapGenerator:
  - name: env-vars
    behavior: replace
    literals:
      - NAMESPACE=model-staging
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: model
    path: patch-rollout-env-selector.yaml
  - path: patch-rollout-podlabels.yaml
  - path: patch-servicemonitor-namespace.yaml
  - path: patch-servicemonitor-port.yaml
  - path: patch-service-active-env.yaml
  - path: patch-service-preview-env.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: model
    path: patch-rollout-analysis-namespace.yaml
images:
  - name: docker.io/joevisco/house-pricemodel
    newTag: sha-test-autopromote
