apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base/model

commonLabels:
  env: staging

namespace: model-staging

patchesStrategicMerge:
  - patch-rollout-podlabels.yaml
  - patch-analysis-namespace.yaml
  - patch-analysistemplate-args.yaml
  - patch-servicemonitor-namespace.yaml
