apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-monitor
  namespace: model-staging
spec:
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
