apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: model
spec:
  strategy:
    blueGreen:
      autoPromotionEnabled: true

  template:
    metadata:
      annotations:
        gitops/restartNonce: "2"
      labels:
        env: staging
