apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: model
spec:
  strategy:
    blueGreen:
      prePromotionAnalysis:
        args:
          - name: namespace
            value: model-staging
