apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - model-rollout.yaml
  - model-active.yaml
  - model-preview.yaml
  - model-servicemonitor.yaml
  - analysis-template.yaml
  - fastapi-scaledobject.yaml
patches:
  - path: patch-rollout-pod-hardening.yaml
  - path: patch-scaledobject-base-prom.yaml
patchesJson6902:
  - target:
      group: keda.sh
      version: v1alpha1
      kind: ScaledObject
      name: fastapi-latency-autoscaler
    path: patch-scaled-object-remove-namespace.json
