apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - model-rollout.yaml
  - model-active.yaml
  - model-preview.yaml
  - model-servicemonitor.yaml
  - analysis-template.yaml
  - fastapi-scaledobject.yaml
