apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: fastapi-latency-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: model # update to your actual deployment name
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 30 # seconds
  cooldownPeriod: 300 # seconds before scaling down
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prom-kube-prometheus-stack-prometheus.default.svc:9090
      metricName: fast_api_latency_p95
      query: histogram_quantile(0.95,sum(rate(http_request_duration_seconds_bucket[1m])) by (le))
      threshold: "0.1"
  - type: cpu
    metricType: Utilization   # Allowed: Utilization | AverageValue
    metadata:
      value: "50" # Scales when average CPU usage > 50%
