apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - model-rollout.yaml
  - model-active.yaml
  - model-preview.yaml
  - streamlit-deploy.yaml
  - streamlit-svc.yaml
  - analysis-template.yaml
