apiVersion: v1
kind: Service
metadata:
  name: model-active
  namespace: default
  labels:
    app: model
spec:
  type: NodePort
  selector:
    app: model
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30100
    protocol: TCP
  - name: metrics
    port: 9100
    targetPort: 9100
    nodePort: 30521
    protocol: TCP
