apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"model"},"name":"model","namespace":"default"},"spec":{"ports":[{"name":"8000","nodePort":30100,"port":8000,"protocol":"TCP","targetPort":8000},{"name":"metrics","port":9100,"targetPort":9100}],"selector":{"app":"model"},"type":"NodePort"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2026-01-31T17:14:09Z"
  labels:
    app: model
  name: model
  namespace: default
  resourceVersion: "1673"
  uid: a2dd6c28-ff57-46f6-9af8-faf5019ed292
spec:
  clusterIP: 10.96.140.131
  clusterIPs:
  - 10.96.140.131
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: "8000"
    nodePort: 30100
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: metrics
    nodePort: 30521
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: model
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
